### ISSUE TITLE
Fails with excess flood when the message is multiline

### ISSUE THREAD

**Issue by oakkitten** [Gottox/irc-message-action#10]
I've got `Comit message: ${{github.event.head_commit.message}}` as a part of bot's message, and commit messages can be multiline. When the number of line is a bit high (10?) the bot fails to transmit anything and there's this in the logs

> ERROR :Closing Link: 1.2.3.4 (Excess Flood)

**Comment by Gottox** [comment]
Thanks for the report. I added excess flood prevention in main. Does that fix your issue? check the new `excess_flood` option.

**Comment by oakkitten** [comment]
Thanks, all lines get printed now!
