### ISSUE TITLE
Node.js 12 actions are deprecated

### ISSUE THREAD

**Issue by The-Compiler** [Gottox/irc-message-action#13]
I [started getting](https://github.com/qutebrowser/qutebrowser/actions/runs/3231901883) these warnings on my actions:

> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: Gottox/irc-message-action

**Comment by DominusExult** [comment]
AFAICT only actions.yml needs `using: 'node16'` instead of node12. @Gottox could you fix this, please?
